#ifndef TOKEN_TYPE_H
#define TOKEN_TYPE_H

#define TOKENIZER_TOKEN_TYPE_KEYWORD_DISTINCT			0
#define TOKENIZER_TOKEN_TYPE_KEYWORD_DOES				0x0100
#define TOKENIZER_TOKEN_TYPE_KEYWORD_GOAL				0x0200
#define TOKENIZER_TOKEN_TYPE_KEYWORD_INIT				0x0300
#define TOKENIZER_TOKEN_TYPE_KEYWORD_LEGAL				0x0400
#define TOKENIZER_TOKEN_TYPE_KEYWORD_NEXT				0x0500
#define TOKENIZER_TOKEN_TYPE_KEYWORD_ROLE				0x0600
#define TOKENIZER_TOKEN_TYPE_KEYWORD_TERMINAL			0x0700
#define TOKENIZER_TOKEN_TYPE_KEYWORD_TRUE				0x0800
#define TOKENIZER_TOKEN_TYPE_KEYWORD_BASE				0x0900
#define TOKENIZER_TOKEN_TYPE_KEYWORD_INPUT				0x0A00

#define TOKENIZER_TOKEN_TYPE_TERM						1
#define TOKENIZER_TOKEN_TYPE_OPEN						2
#define TOKENIZER_TOKEN_TYPE_CLOSE						3
#define TOKENIZER_TOKEN_TYPE_VAR						4

#define TOKENIZER_TOKEN_TYPE_OPERATOR_IF				5
#define TOKENIZER_TOKEN_TYPE_OPERATOR_NOT				0x0105
#define TOKENIZER_TOKEN_TYPE_OPERATOR_OR				0x0305

#endif